### ISSUE TITLE
imt.savefig.py only saving images at 72 dpi

### ISSUE THREAD

**Issue by elliottwarren** [SciTools-incubator/image-meta-tag#137]
imt.image_file_postproc() in imt.savefig() is changing or resaving the dpi of figures to 72, when the original dpi could be much higher (e.g. 300). 

Code snippet to recreate the issue:

import ImageMetaTag as imt

pathname = '/home/h01/ewarren/cylc-run/u-al685_TCbogus_highres/share/data/Plots/tcver/u-ck824_v_u-co412/FS_Central_Pressure_Bias.png'

img_tags = {'aggperiod': 'None',
 'datatimes': 'QG',
 'dates': 'None',
 'fcrs': 'None',
 'period': 'None',
 'difference': 'None',
 'grid': 'None',
 'scales': 'None',
 'stations': 'None',
 'levels': 'None',
 'params': 'None',
 'truth': 'None',
 'fields': 'Central Pressure',
 'probbins': 'None',
 'areas': 'Global',
 'expid': 'u-ck824 Vs u-co412',
 'plot type': 'Forecast',
 'stats': 'Bias',
 'thresh': 'None',
 'tiletype': 'None',
 'storm name': 'None'}

imt.image_file_postproc(pathname, img_tags=img_tags)

Example image (with a dpi of 100 before being passed through imt.image_file_postproc()):
![FS_Central_Pressure_Bias](https://user-images.githubusercontent.com/26275660/181214283-e72fa80f-1329-4a46-94eb-06e1a0e03f50.png)

**Comment by melissaebrooks** [comment]
branch: 137-imtsavefigpy-only-saving-images-at-72-dpi
