### ISSUE TITLE
Installing ImageMetaTag into https://github.com/SciTools/conda-recipes-scitools

### ISSUE THREAD

**Issue by malcolmbrooks** [SciTools-incubator/image-meta-tag#51]
The software stack for SciTools is controlled under:
https://github.com/SciTools/conda-recipes-scitools

To roll out changes in ImageMetaTag into the stack, we need to make a branch to it, and make a pull request for it to be merged.

This issue covers changes required for this to happen.

**Comment by malcolmbrooks** [comment]
https://github.com/SciTools/conda-recipes-scitools/pull/209   Covers first attempt to include vn0.4.1

**Comment by malcolmbrooks** [comment]
The conda recipes for scitools have been retired (https://github.com/SciTools/conda-recipes-scitools) and we are now recommended to add recipes to the newer https://github.com/conda-forge/staged-recipes 

The conda-forge recipes are supported by a wider and more diverse community with direct support and involvement with conda maintainers etc.

https://github.com/conda-forge/staged-recipes/pull/3970 aimed to add a recipe for ImageMetaTag vn0.6.3 to conda-forge.

Updates to the setup.py meant release increments to vn0.6.5.

**Comment by pelson** [comment]
Looks like this got done! 🎉
